version: '2'

services:
  traptor:
    build: .
    container_name: traptor
    volumes:
      - .:/code
      - ./logs:/var/log/traptor
    depends_on:
      - redis
      - kafka
      - zookeeper
      - elasticsearch
      - logstash
      - kibana
    restart: always

  redis:
    container_name: traptor_redis
    image: redis:latest
    ports:
      - "6379"

  kafka:
    container_name: traptor_kafka
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    container_name: traptor_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  elasticsearch:
    container_name: traptor_elasticsearch
    image: elasticsearch

  logstash:
    container_name: traptor_logstash
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/traptor-logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs:/var/log/traptor

  kibana:
    container_name: traptor_kibana
    image: kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200