version: '2'

services:

  traptor:
    build: .
    container_name: traptor
    volumes:
      - .:/code
      - ./logs:/var/log/traptor
    environment:
      - TRAPTOR_TYPE=track
      - TRAPTOR_ID=0
      - RULE_CHECK_INTERVAL=60
      - USE_SENTRY='false'
      - SENTRY_URL=https://www.google.com
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor.log
      - KAFKA_ENABLED='true'
      - KAFKA_HOSTS=kafka:9092
      - KAFKA_TOPIC=traptor.testing
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=5
      - REDIS_PUBSUB_CHANNEL=traptor-test
      - CONSUMER_KEY=
      - CONSUMER_SECRET=
      - ACCESS_TOKEN=
      - ACCESS_TOKEN_SECRET=
    depends_on:
      - logstash
      - zookeeper
      - kafka
      - redis
      - elasticsearch
      - kibana
    restart: always

  redis:
    container_name: traptor_redis
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    container_name: traptor_kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    container_name: traptor_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  elasticsearch:
    container_name: traptor_elasticsearch
    image: elasticsearch

  logstash:
    container_name: traptor_logstash
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/traptor-logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs:/var/log/traptor

  kibana:
    container_name: traptor_kibana
    image: kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200