version: '2'

services:

  traptor:
    build: .
    volumes:
      - .:/code
      - ./logs:/var/log/traptor
    env_file:
      - ./traptor.env
    depends_on:
      # - logstash
      # - zookeeper
      # - kafka
      - redis
      # - elasticsearch
      # - kibana
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  elasticsearch:
    image: elasticsearch:latest

  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/traptor-logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs:/var/log/traptor

  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200