version: '2'

services:

  traptor:
    build: .
    volumes:
      - .:/code
      - ./logs:/var/log/traptor
    env_file:
      - ./traptor.env
    depends_on:
      - redis
#      - kafka
#      - elasticsearch
#      - kopf
#      - logstash
#      - kibana
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=2
      - KAFKA_HOSTS=kafka:9092
      - TRAPTOR_TYPE=track
      - TRAPTOR_ID=0
      - RULE_CHECK_INTERVAL=5
      - USE_SENTRY=false
      - SENTRY_URL=https://SENTRY_UN:SENTRY_PW@sentry.io/55250
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/traptor
      - LOG_FILE_NAME=traptor.log
      - KAFKA_ENABLED=true
      - KAFKA_TOPIC=traptor
      - REDIS_PUBSUB_CHANNEL=traptor-notify
      # - CONSUMER_KEY=TRACK_IST_CK_1
      # - CONSUMER_SECRET=TRACK_IST_CS_1
      # - ACCESS_TOKEN=TRACK_IST_AT_1
      # - ACCESS_TOKEN_SECRET=TRACK_IST_ATS_1
    restart: always

  redis:
    image: redis:2.8.17
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  elasticsearch:
    image: elasticsearch:2.4.1
    ports:
      - "9200:9200"

  kopf:
    image: lmenezes/elasticsearch-kopf
    ports:
      - 8080:80
    environment:
      - KOPF_SERVER_NAME=dockerhost
      - KOPF_ES_SERVERS=elasticsearch:9200
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:2.4.0-1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/traptor-logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logs-template.json:/etc/logstash/templates/logs-template.json
      - ./logs:/var/log/traptor

  kibana:
    image: kibana:4.6.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
